name: Manually triggered workflow

on:
  workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Build Image
              run: docker build . --file dev/build/Dockerfile
